<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ИД',
    'Content' => 'Комментарий',
    'Entity' => 'Модель',
    'Entity ID' => 'ИД модели',
    'Parent ID' => 'Родитель',
    'Status' => 'Статус',
    'Level' => 'Уровень',
    'Created by' => 'Создан',
    'Updated by' => 'Обновлен',
    'Related to' => 'Относится к',
    'Created date' => 'Дата создания',
    'Updated date' => 'Дата обновления',
    'Update' => 'Обновить',
    'Delete' => 'Удалить',
    'Reply' => 'Ответить',
    'Comments ({0})' => 'Комментарии ({0})',
    'Comment cannot be blank.' => 'Комментарий не может быть пустым.',
    'Comment has not been deleted. Please try again!' => 'Не удалось удалить комментарий. Попробуйте пожалуйста еще раз!',
    'Add a comment...' => 'Добавить комментарий...',
    'Comment' => 'Опубликовать комментарий',
    'Oops, something went wrong. Please try again later.' => 'Не удалось добавить комментарий. Попробуйте пожалуйста еще раз.',
    'The requested page does not exist.' => 'Ошибка 404 - страница не найдена!',
    'Comment has been deleted.' => 'Комментарий был удалён.',
    'Comment has been saved.' => 'Комментарий был сохранён.',
    'Click here to cancel reply.' => 'Нажмите здесь, чтобы отменить ответ.',
    'Comments Management' => 'Управление Комментариями',
    'Select Status' => 'Выберите Статус',
    'Select Author' => 'Выберите Автора',
    'Update Comment: {0}' => 'Обновить комментарий: {0}',
    'Active' => 'Включён',
    'Deleted' => 'Удален',
    'Go Back' => 'Вернуться'
];
