<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Content' => 'Content',
    'Entity' => 'Entity',
    'Entity ID' => 'Entity ID',
    'Parent ID' => 'Parent ID',
    'Status' => 'Status',
    'Level' => 'Level',
    'Created by' => 'Created by',
    'Updated by' => 'Related to',
    'Related to' => 'Related to',
    'Url' => 'Url',
    'Created date' => 'Created date',
    'Updated date' => 'Updated date',
    'View' => 'View',
    'Update' => 'Update',
    'Delete' => 'Delete',
    'Reply' => 'Reply',
    'Comments ({0})' => 'Comments ({0})',
    'Comment cannot be blank.' => 'Comment cannot be blank.',
    'Comment has not been deleted. Please try again!' => 'Comment has not been deleted. Please try again!',
    'Add a comment...' => 'Add a comment...',
    'Comment' => 'Comment',
    'Oops, something went wrong. Please try again later.' => 'Oops, something went wrong. Please try again later.',
    'The requested page does not exist.' => 'The requested page does not exist.',
    'Comment has been deleted.' => 'Comment has been deleted.',
    'Comment has been saved.' => 'Comment has been saved.',
    'Click here to cancel reply.' => 'Click here to cancel reply.',
    'Comments Management' => 'Comments Management',
    'Select Status' => 'Select Status',
    'Select Author' => 'Select Author',
    'Update Comment: {0}' => 'Update Comment: {0}',
    'Active' => 'Active',
    'Deleted' => 'Deleted',
    'Go Back' => 'Go Back',
];
