<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Content' => 'Conteúdo',
    'Entity' => 'Entidade',
    'Entity ID' => 'ID da Entidade',
    'Parent ID' => 'ID Pai',
    'Status' => 'Situação',
    'Level' => 'Level',
    'Created by' => 'Criado por',
    'Updated by' => 'Alterado por',
    'Related to' => 'Relacionado por',
    'Url' => 'Url',
    'Created date' => 'Criado em',
    'Updated date' => 'Alterado em',
    'View' => 'Visualizar',
    'Update' => 'Alterar',
    'Delete' => 'Excluir',
    'Reply' => 'Responder',
    'Comments ({0})' => 'Comentários ({0})',
    'Comment cannot be blank.' => 'Comentário não pode ficar em branco.',
    'Comment has not been deleted. Please try again!' => 'Comentário não pode ser excluído. Tente novamente!',
    'Add a comment...' => 'Adicionar Comentário...',
    'Comment' => 'Comentário',
    'Oops, something went wrong. Please try again later.' => 'Oops, algo deu errado. Tente novamente depois.',
    'The requested page does not exist.' => 'Página solicitada não existe.',
    'Comment has been deleted.' => 'Comentário foi excluído.',
    'Comment has been saved.' => 'Comentário foi gravado.',
    'Click here to cancel reply.' => 'Clique aqui para cancelar a resposta.',
    'Comments Management' => 'Gerenciar Comentários',
    'Select Status' => 'Selecionar situação',
    'Select Author' => 'Selecionar Autor',
    'Update Comment: {0}' => 'Alterar  Comentário: {0}',
    'Active' => 'Ativo',
    'Deleted' => 'Excluído',
    'Go Back' => 'Voltar',
];
